services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: portal-sugestao-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Local_dev_only_123!"
    ports:
      - "1433:1433"
    volumes:
      - portal-sugestao-sqldata:/var/opt/mssql

volumes:
  portal-sugestao-sqldata:
